"""Разбор страницы статьи: тело, которое не про её заголовок (Eni, 25.09).

У Eni на каждой странице висит виджет чат-бота EnergIA — bootstrap-окно `.modal-content`.
Тело статьи лежит в `div.container-body`, у которого нет ни одного «статейного» класса,
поэтому основное извлечение брало окно чат-бота: 3177 одинаковых знаков у всех страниц,
первая такая «статья» легла в базу, остальные молча отбивал рубеж «то же тело».
Страж принадлежности (№24) уже стоял в дозагрузке, но не на первичном разборе.
"""

import pytest

from oiltech_digest.ingestion import article_page

ENI_TITLE = "Eni awarded a new exploration licence in the prolific Kutei Basin, Indonesia"
ENI_ARTICLE = (
    "San Donato Milanese, 24 September 2026 – Eni confirms the award of the Sapukala block with 100% "
    "participating interest in the Kutei Basin, in Indonesia, within the first Indonesia Petroleum Bidding Round.",
    "The Sapukala offshore block covers a large area in the deep-water sector of the Kutei Basin, East "
    "Kalimantan, adjacent to the blocks Eni already operates and close to the future North Hub developments.",
    "The award strengthens the company's position in one of its core exploration areas and supports the "
    "strategy of near-field exploration around existing production hubs.",
)
ENI_CHAT = (
    "If you want to change topic, clear the chat and make a new query to receive more relevant results.",
    "This will delete the question history and start a new conversation with the virtual assistant.",
    "Here you can find the answers generated by the assistant on the basis of the published contents.",
    "The answers may contain inaccuracies: always check the information on the official pages.",
)
ENI_LIKE_HTML = f"""<html><head><meta property="og:title" content="{ENI_TITLE}"></head><body>
<div class="hero"><h1 class="eni-h2">{ENI_TITLE}</h1></div>
<div class="one-colonna-body"><div class="container-body"><div class="paragraph">
{''.join(f'<p>{p}</p>' for p in ENI_ARTICLE)}
</div></div></div>
<div class="modal fade" id="modalGenAI" aria-hidden="true"><div class="modal-dialog"><div class="modal-content">
{''.join(f'<p>{p}</p>' for p in ENI_CHAT)}
</div></div></div>
</body></html>""".encode()

OWN_ARTICLE_HTML = b"""<html><head>
<meta property="og:title" content="Field automation rollout improves wellsite performance"></head><body>
<article>
  <p>The company deployed a field automation stack across producing wells and surface facilities.</p>
  <p>The program reduced manual interventions, improved uptime and gave engineers better production control.</p>
  <p>Additional industrial context keeps this article above teaser length and suitable for downstream AI stages.</p>
</article></body></html>"""


def test_text_not_about_the_title_gives_way_to_second_extractor(monkeypatch):
    own = "\n".join(ENI_ARTICLE)
    monkeypatch.setattr(article_page, "_trafilatura_extract", lambda content: own)

    title, _, text = article_page.parse_article_page(ENI_LIKE_HTML)

    assert title == ENI_TITLE
    assert text == own


def test_widget_page_gives_own_article_text_with_real_second_extractor():
    pytest.importorskip("trafilatura")

    _, _, text = article_page.parse_article_page(ENI_LIKE_HTML)

    assert "Sapukala block" in text
    assert "clear the chat" not in text


def test_text_about_the_title_does_not_call_second_extractor(monkeypatch):
    def forbidden(content):
        raise AssertionError("своя статья уже извлечена — второй разбор не нужен")

    monkeypatch.setattr(article_page, "_trafilatura_extract", forbidden)

    _, _, text = article_page.parse_article_page(OWN_ARTICLE_HTML)

    assert "field automation stack" in text


def test_foreign_text_stays_when_second_extractor_is_not_about_the_title_either(monkeypatch):
    # Хуже, чем было, не делаем: второй разбор тоже чужой — остаётся то, что взяли раньше
    # (дальше его ловит рубеж «то же тело», и отказ виден в логе).
    other = "Quarterly dividend policy of an unrelated retail company explained in detail. " * 4
    monkeypatch.setattr(article_page, "_trafilatura_extract", lambda content: other)

    _, _, text = article_page.parse_article_page(ENI_LIKE_HTML)

    assert "clear the chat" in text
